# coding: utf-8

"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapiclient
from openapiclient.models.lockfile_add_lockfile_request_body import LockfileAddLockfileRequestBody  # noqa: E501
from openapiclient.rest import ApiException

class TestLockfileAddLockfileRequestBody(unittest.TestCase):
    """LockfileAddLockfileRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test LockfileAddLockfileRequestBody
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LockfileAddLockfileRequestBody`
        """
        model = openapiclient.models.lockfile_add_lockfile_request_body.LockfileAddLockfileRequestBody()  # noqa: E501
        if include_optional :
            return LockfileAddLockfileRequestBody(
                file_content = '', 
                path = '/FutureVuls/package.json', 
                server_id = 1
            )
        else :
            return LockfileAddLockfileRequestBody(
                file_content = '',
                path = '/FutureVuls/package.json',
                server_id = 1,
        )
        """

    def testLockfileAddLockfileRequestBody(self):
        """Test LockfileAddLockfileRequestBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
