# coding: utf-8

"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapiclient
from openapiclient.models.need_restart_proc_response_body import NeedRestartProcResponseBody  # noqa: E501
from openapiclient.rest import ApiException

class TestNeedRestartProcResponseBody(unittest.TestCase):
    """NeedRestartProcResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test NeedRestartProcResponseBody
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NeedRestartProcResponseBody`
        """
        model = openapiclient.models.need_restart_proc_response_body.NeedRestartProcResponseBody()  # noqa: E501
        if include_optional :
            return NeedRestartProcResponseBody(
                init_system = 'initSystem', 
                path = 'path', 
                pid = '12', 
                service_name = 'serviceName'
            )
        else :
            return NeedRestartProcResponseBody(
                init_system = 'initSystem',
                path = 'path',
                pid = '12',
                service_name = 'serviceName',
        )
        """

    def testNeedRestartProcResponseBody(self):
        """Test NeedRestartProcResponseBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
