# coding: utf-8

"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapiclient
from openapiclient.models.sec_metric_response_body import SecMetricResponseBody  # noqa: E501
from openapiclient.rest import ApiException

class TestSecMetricResponseBody(unittest.TestCase):
    """SecMetricResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SecMetricResponseBody
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SecMetricResponseBody`
        """
        model = openapiclient.models.sec_metric_response_body.SecMetricResponseBody()  # noqa: E501
        if include_optional :
            return SecMetricResponseBody(
                ar = '', 
                cr = '', 
                created_at = '2018-07-14T08:13:28Z', 
                ir = '', 
                role_id = 1, 
                role_name = 'roleName', 
                updated_at = '2018-07-14T08:13:28Z'
            )
        else :
            return SecMetricResponseBody(
                ar = '',
                cr = '',
                created_at = '2018-07-14T08:13:28Z',
                ir = '',
                role_id = 1,
                role_name = 'roleName',
                updated_at = '2018-07-14T08:13:28Z',
        )
        """

    def testSecMetricResponseBody(self):
        """Test SecMetricResponseBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
