# coding: utf-8

"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapiclient
from openapiclient.models.affected_proc_response_body import AffectedProcResponseBody  # noqa: E501
from openapiclient.rest import ApiException

class TestAffectedProcResponseBody(unittest.TestCase):
    """AffectedProcResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AffectedProcResponseBody
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AffectedProcResponseBody`
        """
        model = openapiclient.models.affected_proc_response_body.AffectedProcResponseBody()  # noqa: E501
        if include_optional :
            return AffectedProcResponseBody(
                name = 'apache', 
                pid = '12'
            )
        else :
            return AffectedProcResponseBody(
                name = 'apache',
                pid = '12',
        )
        """

    def testAffectedProcResponseBody(self):
        """Test AffectedProcResponseBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
