# coding: utf-8

"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapiclient
from openapiclient.models.pkg_cpe_add_cpe_request_body import PkgCpeAddCpeRequestBody  # noqa: E501
from openapiclient.rest import ApiException

class TestPkgCpeAddCpeRequestBody(unittest.TestCase):
    """PkgCpeAddCpeRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PkgCpeAddCpeRequestBody
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PkgCpeAddCpeRequestBody`
        """
        model = openapiclient.models.pkg_cpe_add_cpe_request_body.PkgCpeAddCpeRequestBody()  # noqa: E501
        if include_optional :
            return PkgCpeAddCpeRequestBody(
                cpe_name = 'cpe:/a:berlios:discussion_forum_2k:3.3', 
                is_uri = True, 
                server_id = 1
            )
        else :
            return PkgCpeAddCpeRequestBody(
                cpe_name = 'cpe:/a:berlios:discussion_forum_2k:3.3',
                server_id = 1,
        )
        """

    def testPkgCpeAddCpeRequestBody(self):
        """Test PkgCpeAddCpeRequestBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
