# coding: utf-8

"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapiclient
from openapiclient.api.role_api import RoleApi  # noqa: E501
from openapiclient.rest import ApiException


class TestRoleApi(unittest.TestCase):
    """RoleApi unit test stubs"""

    def setUp(self):
        self.api = openapiclient.api.role_api.RoleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_role_delete_role(self):
        """Test case for role_delete_role

        deleteRole role  # noqa: E501
        """
        pass

    def test_role_get_role_detail(self):
        """Test case for role_get_role_detail

        getRoleDetail role  # noqa: E501
        """
        pass

    def test_role_get_role_list(self):
        """Test case for role_get_role_list

        getRoleList role  # noqa: E501
        """
        pass

    def test_role_update_role(self):
        """Test case for role_update_role

        updateRole role  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
