# coding: utf-8

"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapiclient
from openapiclient.models.pkg_cpe_child_response_body import PkgCpeChildResponseBody  # noqa: E501
from openapiclient.rest import ApiException

class TestPkgCpeChildResponseBody(unittest.TestCase):
    """PkgCpeChildResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PkgCpeChildResponseBody
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PkgCpeChildResponseBody`
        """
        model = openapiclient.models.pkg_cpe_child_response_body.PkgCpeChildResponseBody()  # noqa: E501
        if include_optional :
            return PkgCpeChildResponseBody(
                affected_procs = [{"name":"apache","pid":"12"},{"name":"apache","pid":"12"},{"name":"apache","pid":"12"},{"name":"apache","pid":"12"}], 
                cpe_id = 1, 
                cpe_uri = 'cpe:2.3:a:clamav:clamav:*:*:*:*:*:*:*:*', 
                created_at = '2018-07-14T08:13:28Z', 
                name = 'package01', 
                new_release = 'new release', 
                new_version = '2.0', 
                pkg_id = 1, 
                release = 'release', 
                repository = 'repository', 
                server_id = 1, 
                updated_at = '2018-07-14T08:13:28Z', 
                version = '1.0'
            )
        else :
            return PkgCpeChildResponseBody(
                created_at = '2018-07-14T08:13:28Z',
                name = 'package01',
                server_id = 1,
                updated_at = '2018-07-14T08:13:28Z',
                version = '1.0',
        )
        """

    def testPkgCpeChildResponseBody(self):
        """Test PkgCpeChildResponseBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
