# coding: utf-8

"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapiclient
from openapiclient.models.cvss_response_body_max_cvss_v2 import CvssResponseBodyMaxCvssV2  # noqa: E501
from openapiclient.rest import ApiException

class TestCvssResponseBodyMaxCvssV2(unittest.TestCase):
    """CvssResponseBodyMaxCvssV2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CvssResponseBodyMaxCvssV2
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CvssResponseBodyMaxCvssV2`
        """
        model = openapiclient.models.cvss_response_body_max_cvss_v2.CvssResponseBodyMaxCvssV2()  # noqa: E501
        if include_optional :
            return CvssResponseBodyMaxCvssV2(
                type = '', 
                value = openapiclient.models.value.value()
            )
        else :
            return CvssResponseBodyMaxCvssV2(
        )
        """

    def testCvssResponseBodyMaxCvssV2(self):
        """Test CvssResponseBodyMaxCvssV2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
