# coding: utf-8

"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapiclient
from openapiclient.models.cwe_response_body import CweResponseBody  # noqa: E501
from openapiclient.rest import ApiException

class TestCweResponseBody(unittest.TestCase):
    """CweResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CweResponseBody
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CweResponseBody`
        """
        model = openapiclient.models.cwe_response_body.CweResponseBody()  # noqa: E501
        if include_optional :
            return CweResponseBody(
                cwe_id = 'CWE-416', 
                english = 'english summary', 
                japanese = 'japanese summary', 
                owasp_top_ten2017 = '10'
            )
        else :
            return CweResponseBody(
                cwe_id = 'CWE-416',
                english = 'english summary',
                japanese = 'japanese summary',
        )
        """

    def testCweResponseBody(self):
        """Test CweResponseBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
