# coding: utf-8

"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapiclient
from openapiclient.models.detection_tool_response_body import DetectionToolResponseBody  # noqa: E501
from openapiclient.rest import ApiException

class TestDetectionToolResponseBody(unittest.TestCase):
    """DetectionToolResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test DetectionToolResponseBody
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DetectionToolResponseBody`
        """
        model = openapiclient.models.detection_tool_response_body.DetectionToolResponseBody()  # noqa: E501
        if include_optional :
            return DetectionToolResponseBody(
                name = 'changelog', 
                patch_applied_at = '2018-07-14T08:13:28Z'
            )
        else :
            return DetectionToolResponseBody(
                name = 'changelog',
        )
        """

    def testDetectionToolResponseBody(self):
        """Test DetectionToolResponseBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
