# coding: utf-8

"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapiclient
from openapiclient.models.task_update_task_request_body import TaskUpdateTaskRequestBody  # noqa: E501
from openapiclient.rest import ApiException

class TestTaskUpdateTaskRequestBody(unittest.TestCase):
    """TaskUpdateTaskRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TaskUpdateTaskRequestBody
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaskUpdateTaskRequestBody`
        """
        model = openapiclient.models.task_update_task_request_body.TaskUpdateTaskRequestBody()  # noqa: E501
        if include_optional :
            return TaskUpdateTaskRequestBody(
                applying_patch_on = 'Sat Jul 14 00:00:00 UTC 2018', 
                main_user_id = 1, 
                priority = 'none', 
                status = 'new', 
                sub_user_id = 2
            )
        else :
            return TaskUpdateTaskRequestBody(
        )
        """

    def testTaskUpdateTaskRequestBody(self):
        """Test TaskUpdateTaskRequestBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
