# coding: utf-8

"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapiclient
from openapiclient.models.child_task_response_body import ChildTaskResponseBody  # noqa: E501
from openapiclient.rest import ApiException

class TestChildTaskResponseBody(unittest.TestCase):
    """ChildTaskResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ChildTaskResponseBody
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChildTaskResponseBody`
        """
        model = openapiclient.models.child_task_response_body.ChildTaskResponseBody()  # noqa: E501
        if include_optional :
            return ChildTaskResponseBody(
                applying_patch_on = '2018-07-14T08:13:28Z', 
                created_at = '2018-07-14T08:13:28Z', 
                cve_id = 'CVE-2017-6799', 
                id = 1, 
                ignore = True, 
                ignore_until = 'vector', 
                main_user_id = 1, 
                main_user_name = 'main-user-name', 
                priority = 'high', 
                server_id = 1, 
                status = 'new', 
                sub_user_id = 1, 
                sub_user_name = 'sub-user-name', 
                updated_at = '2018-07-14T08:13:28Z'
            )
        else :
            return ChildTaskResponseBody(
                created_at = '2018-07-14T08:13:28Z',
                cve_id = 'CVE-2017-6799',
                id = 1,
                ignore = True,
                priority = 'high',
                server_id = 1,
                status = 'new',
                updated_at = '2018-07-14T08:13:28Z',
        )
        """

    def testChildTaskResponseBody(self):
        """Test ChildTaskResponseBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
