# coding: utf-8

"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapiclient
from openapiclient.api.group_set_cve_api import GroupSetCveApi  # noqa: E501
from openapiclient.rest import ApiException


class TestGroupSetCveApi(unittest.TestCase):
    """GroupSetCveApi unit test stubs"""

    def setUp(self):
        self.api = openapiclient.api.group_set_cve_api.GroupSetCveApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_group_set_cve_get_group_set_cve_detail(self):
        """Test case for group_set_cve_get_group_set_cve_detail

        getGroupSetCveDetail groupSetCve  # noqa: E501
        """
        pass

    def test_group_set_cve_get_group_set_cve_list(self):
        """Test case for group_set_cve_get_group_set_cve_list

        getGroupSetCveList groupSetCve  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
