# coding: utf-8

"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapiclient
from openapiclient.models.group_response_body import GroupResponseBody  # noqa: E501
from openapiclient.rest import ApiException

class TestGroupResponseBody(unittest.TestCase):
    """GroupResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GroupResponseBody
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupResponseBody`
        """
        model = openapiclient.models.group_response_body.GroupResponseBody()  # noqa: E501
        if include_optional :
            return GroupResponseBody(
                id = 1, 
                group_name = 'CWE-416'
            )
        else :
            return GroupResponseBody(
                id = 1,
                group_name = 'CWE-416',
        )
        """

    def testGroupResponseBody(self):
        """Test GroupResponseBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
