# coding: utf-8

"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapiclient
from openapiclient.models.cve_child_response_body import CveChildResponseBody  # noqa: E501
from openapiclient.rest import ApiException

class TestCveChildResponseBody(unittest.TestCase):
    """CveChildResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CveChildResponseBody
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CveChildResponseBody`
        """
        model = openapiclient.models.cve_child_response_body.CveChildResponseBody()  # noqa: E501
        if include_optional :
            return CveChildResponseBody(
                advisory_ids = ["advisoryID"], 
                cve_id = 'CVE-2018-1234', 
                cwes = [{"cweID":"CWE-416","english":"english summary","japanese":"japanese summary","owaspTopTen2017":"10"},{"cweID":"CWE-416","english":"english summary","japanese":"japanese summary","owaspTopTen2017":"10"},{"cweID":"CWE-416","english":"english summary","japanese":"japanese summary","owaspTopTen2017":"10"},{"cweID":"CWE-416","english":"english summary","japanese":"japanese summary","owaspTopTen2017":"10"}], 
                exploit_level = 'Qui rerum vero.', 
                has_exploit = True, 
                has_mitigation = True, 
                is_owasp_top_ten2017 = True, 
                max_v2 = 9.0, 
                max_v3 = 9.0, 
                pkg_fixed_status = 'Hic et vel dolorem atque nisi nihil.', 
                pkg_fixed_status_name = 'Eveniet fugit et porro molestias quos autem.', 
                score_v2s = {"nvd":9,"redhat":7}, 
                score_v3s = {"nvd":8,"redhat":9}, 
                title = 'title', 
                vector_v2s = {"jvn":"AV:L/AC:M/Au:N/C:C/I:N/A:N","nvd":"AV:L/AC:M/Au:N/C:C/I:N/A:N"}, 
                vector_v3s = {"jvn":"AV:L/AC:H/PR:L/UI:N/S:C/C:H/I:N/A:N","nvd":"AV:L/AC:H/PR:L/UI:N/S:C/C:H/I:N/A:N"}
            )
        else :
            return CveChildResponseBody(
                advisory_ids = ["advisoryID"],
                cve_id = 'CVE-2018-1234',
                cwes = [{"cweID":"CWE-416","english":"english summary","japanese":"japanese summary","owaspTopTen2017":"10"},{"cweID":"CWE-416","english":"english summary","japanese":"japanese summary","owaspTopTen2017":"10"},{"cweID":"CWE-416","english":"english summary","japanese":"japanese summary","owaspTopTen2017":"10"},{"cweID":"CWE-416","english":"english summary","japanese":"japanese summary","owaspTopTen2017":"10"}],
                is_owasp_top_ten2017 = True,
                max_v2 = 9.0,
                max_v3 = 9.0,
                score_v2s = {"nvd":9,"redhat":7},
                score_v3s = {"nvd":8,"redhat":9},
                title = 'title',
                vector_v2s = {"jvn":"AV:L/AC:M/Au:N/C:C/I:N/A:N","nvd":"AV:L/AC:M/Au:N/C:C/I:N/A:N"},
                vector_v3s = {"jvn":"AV:L/AC:H/PR:L/UI:N/S:C/C:H/I:N/A:N","nvd":"AV:L/AC:H/PR:L/UI:N/S:C/C:H/I:N/A:N"},
        )
        """

    def testCveChildResponseBody(self):
        """Test CveChildResponseBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
