# coding: utf-8

"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapiclient
from openapiclient.models.server_create_pkg_paste_server_request_body import ServerCreatePkgPasteServerRequestBody  # noqa: E501
from openapiclient.rest import ApiException

class TestServerCreatePkgPasteServerRequestBody(unittest.TestCase):
    """ServerCreatePkgPasteServerRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ServerCreatePkgPasteServerRequestBody
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServerCreatePkgPasteServerRequestBody`
        """
        model = openapiclient.models.server_create_pkg_paste_server_request_body.ServerCreatePkgPasteServerRequestBody()  # noqa: E501
        if include_optional :
            return ServerCreatePkgPasteServerRequestBody(
                kernel_release = 'kernel release', 
                kernel_version = 'kernel version', 
                os_family = '20', 
                os_version = '20', 
                pkg_paste_text = 'grub2-tools 1 2.02 0.80.el7 x86_64', 
                server_name = 'Server Name'
            )
        else :
            return ServerCreatePkgPasteServerRequestBody(
                kernel_release = 'kernel release',
                os_family = '20',
                os_version = '20',
                pkg_paste_text = 'grub2-tools 1 2.02 0.80.el7 x86_64',
                server_name = 'Server Name',
        )
        """

    def testServerCreatePkgPasteServerRequestBody(self):
        """Test ServerCreatePkgPasteServerRequestBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
