# coding: utf-8

"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, StrictStr

class CvssResponseBodyVulnInfo(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    alert_dict: Optional[Dict[str, Any]] = Field(None, alias="alertDict")
    ctis: Optional[List[StrictStr]] = None
    cve_contents: Optional[Dict[str, Any]] = Field(None, alias="cveContents")
    cve_id: Optional[StrictStr] = Field(None, alias="cveID")
    exploits: Optional[List[Dict[str, Any]]] = None
    mitigations: Optional[List[Dict[str, Any]]] = None
    __properties = ["alertDict", "ctis", "cveContents", "cveID", "exploits", "mitigations"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CvssResponseBodyVulnInfo:
        """Create an instance of CvssResponseBodyVulnInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CvssResponseBodyVulnInfo:
        """Create an instance of CvssResponseBodyVulnInfo from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return CvssResponseBodyVulnInfo.parse_obj(obj)

        _obj = CvssResponseBodyVulnInfo.parse_obj({
            "alert_dict": obj.get("alertDict"),
            "ctis": obj.get("ctis"),
            "cve_contents": obj.get("cveContents"),
            "cve_id": obj.get("cveID"),
            "exploits": obj.get("exploits"),
            "mitigations": obj.get("mitigations")
        })
        return _obj

