# coding: utf-8

"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr

class CweResponseBody(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    cwe_id: StrictStr = Field(..., alias="cweID", description="cweID of cwe")
    english: StrictStr = Field(..., description="english summary of cwe")
    japanese: StrictStr = Field(..., description="japanese summary of cwe")
    owasp_top_ten2017: Optional[StrictStr] = Field(None, alias="owaspTopTen2017", description="owaspTopTen2017 of cwe ")
    __properties = ["cweID", "english", "japanese", "owaspTopTen2017"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CweResponseBody:
        """Create an instance of CweResponseBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CweResponseBody:
        """Create an instance of CweResponseBody from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return CweResponseBody.parse_obj(obj)

        _obj = CweResponseBody.parse_obj({
            "cwe_id": obj.get("cweID"),
            "english": obj.get("english"),
            "japanese": obj.get("japanese"),
            "owasp_top_ten2017": obj.get("owaspTopTen2017")
        })
        return _obj

