# coding: utf-8

"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json

from datetime import datetime

from pydantic import BaseModel, Field, StrictInt, StrictStr

class EnvMetricV3ResponseBody(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    created_at: datetime = Field(..., alias="createdAt", description="created time")
    cve_id: StrictStr = Field(..., alias="cveID", description="CveID of envMetricV3")
    ma: StrictStr = Field(..., description="MA of envMetricV3")
    mac: StrictStr = Field(..., description="MAC of envMetricV3")
    mav: StrictStr = Field(..., description="MAV of envMetricV3")
    mc: StrictStr = Field(..., description="MC of envMetricV3")
    mpr: StrictStr = Field(..., description="MPR of envMetricV3")
    ms: StrictStr = Field(..., description="MS of envMetricV3")
    mui: StrictStr = Field(..., description="MUI of envMetricV3")
    role_id: StrictInt = Field(..., alias="roleID", description="ServerRoleID of envMetricV3")
    role_name: StrictStr = Field(..., alias="roleName", description="ServerRoleName of envMetricV3")
    updated_at: datetime = Field(..., alias="updatedAt", description="updated time")
    __properties = ["createdAt", "cveID", "ma", "mac", "mav", "mc", "mpr", "ms", "mui", "roleID", "roleName", "updatedAt"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> EnvMetricV3ResponseBody:
        """Create an instance of EnvMetricV3ResponseBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> EnvMetricV3ResponseBody:
        """Create an instance of EnvMetricV3ResponseBody from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return EnvMetricV3ResponseBody.parse_obj(obj)

        _obj = EnvMetricV3ResponseBody.parse_obj({
            "created_at": obj.get("createdAt"),
            "cve_id": obj.get("cveID"),
            "ma": obj.get("ma"),
            "mac": obj.get("mac"),
            "mav": obj.get("mav"),
            "mc": obj.get("mc"),
            "mpr": obj.get("mpr"),
            "ms": obj.get("ms"),
            "mui": obj.get("mui"),
            "role_id": obj.get("roleID"),
            "role_name": obj.get("roleName"),
            "updated_at": obj.get("updatedAt")
        })
        return _obj

