# coding: utf-8

"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Dict, List, Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr
from openapiclient.models.affected_proc_response_body import AffectedProcResponseBody
from openapiclient.models.child_task_response_body import ChildTaskResponseBody
from openapiclient.models.group_response_body import GroupResponseBody
from openapiclient.models.need_restart_proc_response_body import NeedRestartProcResponseBody
from openapiclient.models.server_child_response_body import ServerChildResponseBody

class GroupSetPkgCpeGetGroupSetPkgDetailResponseBody(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    affected_procs: Optional[List[AffectedProcResponseBody]] = Field(None, alias="affectedProcs", description="AffectedProcess list of package")
    created_at: datetime = Field(..., alias="createdAt", description="crated time of package or cpe")
    group: Optional[GroupResponseBody] = None
    id: Optional[StrictInt] = Field(None, description="ID of package")
    name: StrictStr = Field(..., description="Name of package or cpe")
    need_restart_procs: Optional[List[NeedRestartProcResponseBody]] = Field(None, alias="needRestartProcs", description="NeedRestartProcess list of package")
    new_release: Optional[StrictStr] = Field(None, alias="newRelease", description="New Release of package")
    new_version: Optional[StrictStr] = Field(None, alias="newVersion", description="New Version of package")
    package_statuses: Optional[Dict[str, StrictStr]] = Field(None, alias="packageStatuses", description="package status of package")
    release: StrictStr = Field(..., description="Release of package")
    repository: Optional[StrictStr] = Field(None, description="Repository of package")
    server: Optional[ServerChildResponseBody] = None
    tasks: Optional[List[ChildTaskResponseBody]] = Field(None, description="updated time of server")
    updated_at: datetime = Field(..., alias="updatedAt", description="updated time of package or cpe")
    version: StrictStr = Field(..., description="Version of package or cpe")
    __properties = ["affectedProcs", "createdAt", "group", "id", "name", "needRestartProcs", "newRelease", "newVersion", "packageStatuses", "release", "repository", "server", "tasks", "updatedAt", "version"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> GroupSetPkgCpeGetGroupSetPkgDetailResponseBody:
        """Create an instance of GroupSetPkgCpeGetGroupSetPkgDetailResponseBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in affected_procs (list)
        _items = []
        if self.affected_procs:
            for _item in self.affected_procs:
                if _item:
                    _items.append(_item.to_dict())
            _dict['affectedProcs'] = _items
        # override the default output from pydantic by calling `to_dict()` of group
        if self.group:
            _dict['group'] = self.group.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in need_restart_procs (list)
        _items = []
        if self.need_restart_procs:
            for _item in self.need_restart_procs:
                if _item:
                    _items.append(_item.to_dict())
            _dict['needRestartProcs'] = _items
        # override the default output from pydantic by calling `to_dict()` of server
        if self.server:
            _dict['server'] = self.server.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in tasks (list)
        _items = []
        if self.tasks:
            for _item in self.tasks:
                if _item:
                    _items.append(_item.to_dict())
            _dict['tasks'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> GroupSetPkgCpeGetGroupSetPkgDetailResponseBody:
        """Create an instance of GroupSetPkgCpeGetGroupSetPkgDetailResponseBody from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return GroupSetPkgCpeGetGroupSetPkgDetailResponseBody.parse_obj(obj)

        _obj = GroupSetPkgCpeGetGroupSetPkgDetailResponseBody.parse_obj({
            "affected_procs": [AffectedProcResponseBody.from_dict(_item) for _item in obj.get("affectedProcs")] if obj.get("affectedProcs") is not None else None,
            "created_at": obj.get("createdAt"),
            "group": GroupResponseBody.from_dict(obj.get("group")) if obj.get("group") is not None else None,
            "id": obj.get("id"),
            "name": obj.get("name"),
            "need_restart_procs": [NeedRestartProcResponseBody.from_dict(_item) for _item in obj.get("needRestartProcs")] if obj.get("needRestartProcs") is not None else None,
            "new_release": obj.get("newRelease"),
            "new_version": obj.get("newVersion"),
            "package_statuses": obj.get("packageStatuses"),
            "release": obj.get("release"),
            "repository": obj.get("repository"),
            "server": ServerChildResponseBody.from_dict(obj.get("server")) if obj.get("server") is not None else None,
            "tasks": [ChildTaskResponseBody.from_dict(_item) for _item in obj.get("tasks")] if obj.get("tasks") is not None else None,
            "updated_at": obj.get("updatedAt"),
            "version": obj.get("version")
        })
        return _obj

