# coding: utf-8

"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr
from openapiclient.models.affected_proc_response_body import AffectedProcResponseBody

class PkgCpeChildResponseBody(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    affected_procs: Optional[List[AffectedProcResponseBody]] = Field(None, alias="affectedProcs", description="AffectedProcess list of package")
    cpe_id: Optional[StrictInt] = Field(None, alias="cpeID", description="CpeID of cpe")
    cpe_uri: Optional[StrictStr] = Field(None, alias="cpeURI", description="Cpe URI of cpe")
    created_at: datetime = Field(..., alias="createdAt", description="crated time of package or cpe")
    name: StrictStr = Field(..., description="Name of package or cpe")
    new_release: Optional[StrictStr] = Field(None, alias="newRelease", description="New Release of package")
    new_version: Optional[StrictStr] = Field(None, alias="newVersion", description="New Version of package")
    pkg_id: Optional[StrictInt] = Field(None, alias="pkgID", description="Package ID of package")
    release: Optional[StrictStr] = Field(None, description="Release of package")
    repository: Optional[StrictStr] = Field(None, description="Repository of package")
    server_id: StrictInt = Field(..., alias="serverID", description="ServerID of package or cpe")
    updated_at: datetime = Field(..., alias="updatedAt", description="updated time of package or cpe")
    version: StrictStr = Field(..., description="Version of package or cpe")
    __properties = ["affectedProcs", "cpeID", "cpeURI", "createdAt", "name", "newRelease", "newVersion", "pkgID", "release", "repository", "serverID", "updatedAt", "version"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PkgCpeChildResponseBody:
        """Create an instance of PkgCpeChildResponseBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in affected_procs (list)
        _items = []
        if self.affected_procs:
            for _item in self.affected_procs:
                if _item:
                    _items.append(_item.to_dict())
            _dict['affectedProcs'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PkgCpeChildResponseBody:
        """Create an instance of PkgCpeChildResponseBody from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return PkgCpeChildResponseBody.parse_obj(obj)

        _obj = PkgCpeChildResponseBody.parse_obj({
            "affected_procs": [AffectedProcResponseBody.from_dict(_item) for _item in obj.get("affectedProcs")] if obj.get("affectedProcs") is not None else None,
            "cpe_id": obj.get("cpeID"),
            "cpe_uri": obj.get("cpeURI"),
            "created_at": obj.get("createdAt"),
            "name": obj.get("name"),
            "new_release": obj.get("newRelease"),
            "new_version": obj.get("newVersion"),
            "pkg_id": obj.get("pkgID"),
            "release": obj.get("release"),
            "repository": obj.get("repository"),
            "server_id": obj.get("serverID"),
            "updated_at": obj.get("updatedAt"),
            "version": obj.get("version")
        })
        return _obj

