# coding: utf-8

"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr

class PkgCpeAddCpeRequestBody(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    cpe_name: StrictStr = Field(..., alias="cpeName", description="Cpe Name(cpe uri or cpe format string)")
    is_uri: Optional[StrictBool] = Field(True, alias="isURI", description="isURI specifies whether cpeName is in URI format or FormatString format.")
    server_id: StrictInt = Field(..., alias="serverID", description="ServerID")
    __properties = ["cpeName", "isURI", "serverID"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PkgCpeAddCpeRequestBody:
        """Create an instance of PkgCpeAddCpeRequestBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PkgCpeAddCpeRequestBody:
        """Create an instance of PkgCpeAddCpeRequestBody from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return PkgCpeAddCpeRequestBody.parse_obj(obj)

        _obj = PkgCpeAddCpeRequestBody.parse_obj({
            "cpe_name": obj.get("cpeName"),
            "is_uri": obj.get("isURI") if obj.get("isURI") is not None else True,
            "server_id": obj.get("serverID")
        })
        return _obj

