# coding: utf-8

"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr
from openapiclient.models.env_metric_v2_response_body import EnvMetricV2ResponseBody
from openapiclient.models.env_metric_v3_response_body import EnvMetricV3ResponseBody
from openapiclient.models.sec_metric_response_body import SecMetricResponseBody
from openapiclient.models.server_child_response_body import ServerChildResponseBody

class RoleUpdateRoleResponseBody(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    all_task_count: Optional[StrictInt] = Field(None, alias="allTaskCount", description="AllTaskCount of server role")
    created_at: datetime = Field(..., alias="createdAt", description="created time of server role")
    env_metric_v2s: Optional[List[EnvMetricV2ResponseBody]] = Field(None, alias="envMetricV2s", description="envMetricV2s of server role")
    env_metric_v3s: Optional[List[EnvMetricV3ResponseBody]] = Field(None, alias="envMetricV3s", description="envMetricV3s of server role")
    id: StrictInt = Field(..., description="ID of server role")
    is_default: Optional[StrictBool] = Field(None, alias="isDefault", description="isDefault of server role")
    name: StrictStr = Field(..., description="Name of server role")
    new_task_count: Optional[StrictInt] = Field(None, alias="newTaskCount", description="NewTaskCount of server role")
    sec_metric: Optional[SecMetricResponseBody] = Field(None, alias="secMetric")
    servers: Optional[List[ServerChildResponseBody]] = Field(None, description="Servers of server role")
    updated_at: datetime = Field(..., alias="updatedAt", description="updated time of server role")
    __properties = ["allTaskCount", "createdAt", "envMetricV2s", "envMetricV3s", "id", "isDefault", "name", "newTaskCount", "secMetric", "servers", "updatedAt"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> RoleUpdateRoleResponseBody:
        """Create an instance of RoleUpdateRoleResponseBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in env_metric_v2s (list)
        _items = []
        if self.env_metric_v2s:
            for _item in self.env_metric_v2s:
                if _item:
                    _items.append(_item.to_dict())
            _dict['envMetricV2s'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in env_metric_v3s (list)
        _items = []
        if self.env_metric_v3s:
            for _item in self.env_metric_v3s:
                if _item:
                    _items.append(_item.to_dict())
            _dict['envMetricV3s'] = _items
        # override the default output from pydantic by calling `to_dict()` of sec_metric
        if self.sec_metric:
            _dict['secMetric'] = self.sec_metric.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in servers (list)
        _items = []
        if self.servers:
            for _item in self.servers:
                if _item:
                    _items.append(_item.to_dict())
            _dict['servers'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> RoleUpdateRoleResponseBody:
        """Create an instance of RoleUpdateRoleResponseBody from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return RoleUpdateRoleResponseBody.parse_obj(obj)

        _obj = RoleUpdateRoleResponseBody.parse_obj({
            "all_task_count": obj.get("allTaskCount"),
            "created_at": obj.get("createdAt"),
            "env_metric_v2s": [EnvMetricV2ResponseBody.from_dict(_item) for _item in obj.get("envMetricV2s")] if obj.get("envMetricV2s") is not None else None,
            "env_metric_v3s": [EnvMetricV3ResponseBody.from_dict(_item) for _item in obj.get("envMetricV3s")] if obj.get("envMetricV3s") is not None else None,
            "id": obj.get("id"),
            "is_default": obj.get("isDefault"),
            "name": obj.get("name"),
            "new_task_count": obj.get("newTaskCount"),
            "sec_metric": SecMetricResponseBody.from_dict(obj.get("secMetric")) if obj.get("secMetric") is not None else None,
            "servers": [ServerChildResponseBody.from_dict(_item) for _item in obj.get("servers")] if obj.get("servers") is not None else None,
            "updated_at": obj.get("updatedAt")
        })
        return _obj

