# coding: utf-8

"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr

class ServerCreatePkgPasteServerRequestBody(BaseModel):
    """
    ServerCreatePkgPasteServerRequestBody
    """
    kernel_release: StrictStr = Field(..., alias="kernelRelease", description="Kernel Release")
    kernel_version: Optional[StrictStr] = Field(None, alias="kernelVersion", description="Kernel Version")
    os_family: StrictStr = Field(..., alias="osFamily", description="Server OS Family")
    os_version: StrictStr = Field(..., alias="osVersion", description="Server OS Version")
    pkg_paste_text: StrictStr = Field(..., alias="pkgPasteText", description="pkg paste text")
    server_name: StrictStr = Field(..., alias="serverName", description="Server Name")
    __properties = ["kernelRelease", "kernelVersion", "osFamily", "osVersion", "pkgPasteText", "serverName"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ServerCreatePkgPasteServerRequestBody:
        """Create an instance of ServerCreatePkgPasteServerRequestBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ServerCreatePkgPasteServerRequestBody:
        """Create an instance of ServerCreatePkgPasteServerRequestBody from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return ServerCreatePkgPasteServerRequestBody.parse_obj(obj)

        _obj = ServerCreatePkgPasteServerRequestBody.parse_obj({
            "kernel_release": obj.get("kernelRelease"),
            "kernel_version": obj.get("kernelVersion"),
            "os_family": obj.get("osFamily"),
            "os_version": obj.get("osVersion"),
            "pkg_paste_text": obj.get("pkgPasteText"),
            "server_name": obj.get("serverName")
        })
        return _obj

