# coding: utf-8

"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr, validator

class TaskUpdateTaskIgnoreRequestBody(BaseModel):
    """
    TaskUpdateTaskIgnoreRequestBody
    """
    ignore_until: StrictStr = Field(..., alias="ignoreUntil", description="ignore until.")
    __properties = ["ignoreUntil"]

    @validator('ignore_until')
    def ignore_until_validate_enum(cls, v):
        if v not in ('nothing', 'anything', 'forever', 'vector', 'pkg_fix', 'exploit', 'ssvc_priority'):
            raise ValueError("must be one of enum values ('nothing', 'anything', 'forever', 'vector', 'pkg_fix', 'exploit', 'ssvc_priority')")
        return v

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TaskUpdateTaskIgnoreRequestBody:
        """Create an instance of TaskUpdateTaskIgnoreRequestBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TaskUpdateTaskIgnoreRequestBody:
        """Create an instance of TaskUpdateTaskIgnoreRequestBody from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return TaskUpdateTaskIgnoreRequestBody.parse_obj(obj)

        _obj = TaskUpdateTaskIgnoreRequestBody.parse_obj({
            "ignore_until": obj.get("ignoreUntil")
        })
        return _obj

